In [1]:
import numpy as np

## Генерация случайной матрицы

Сгенерируйте матрицу, состоящую из 1000 строк и 50 столбцов, элементы которой являются случайными из нормального распределения N(1,10).

In [4]:
X = np.random.normal(loc=1, scale=10, size=(1000,50))
print X

[[ -4.95214132 -11.84243182  -9.27116245 ...,  -1.59428879 -15.92579186
   -4.61364571]
 [ -7.39918278   2.65843401 -19.90623885 ...,   7.33262054  11.9910464
   -8.70729215]
 [ 14.37909691   6.23900281  13.55970361 ...,  12.9956582  -14.82011738
   -4.21485428]
 ..., 
 [  7.19592409   5.61942935   7.49149973 ...,   5.05283356  -9.14337927
    0.74316059]
 [  6.61865977  14.04483374  -1.06821186 ...,  -3.43462607 -13.0858908
   -3.02206667]
 [ 18.88400678  28.86164324   3.59415901 ..., -13.31918842  16.7865867
   -4.72087015]]


## Нормировка матрицы

Произведите нормировку матрицы из предыдущего задания: вычтите из каждого столбца его среднее значение, а затем поделите на его стандартное отклонение.

In [6]:
# параметр axis, который указывает, по какому измерению вычисляются среднее 
# и стандартное отклонение (если axis=0, то по столбцам, если axis=1, 
# то по строкам; если его не указывать, то данные величины будут вычислены 
# по всей матрице)
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
print X_norm

[[-0.57518318 -1.25433621 -1.00603639 ..., -0.22905812 -1.64799347
  -0.53886797]
 [-0.82124126  0.16561021 -2.08396052 ...,  0.69428195  1.08813585
  -0.93045591]
 [ 1.36863654  0.51622485  1.30799882 ...,  1.28002886 -1.53962631
  -0.50072059]
 ..., 
 [ 0.64634484  0.45555529  0.69295262 ...,  0.45847596 -0.98324921
  -0.02644933]
 [ 0.58829901  1.28058346 -0.17462174 ..., -0.41941036 -1.36965477
  -0.38662152]
 [ 1.82162008  2.73146755  0.29793547 ..., -1.44180368  1.55814675
  -0.54912479]]


 ## Операции над элементами матрицы

Выведите для заданной матрицы номера строк, сумма элементов в которых превосходит 10.

In [7]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [9]:
r = np.sum(Z, axis=1)
print np.nonzero(r>10)

(array([1, 4, 5]),)


## Объединение матриц

Сгенерируйте две единичные матрицы (т.е. с единицами на диагонали) размера 3x3. Соедините две матрицы в одну размера 6x3.

In [10]:
A = np.eye(3)
B = np.eye(3)
print A
print B

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [12]:
AB = np.vstack((A,B))
print AB

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
